# Generated by Django 2.0.5 on 2018-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='workclass',
            name='value',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
