# Generated by Django 2.0.5 on 2018-06-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180610_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='edu_id',
            new_name='edu',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mar_status_id',
            new_name='mar_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='occupation_id',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='race_id',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='relation_id',
            new_name='relation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wrk_cls_id',
            new_name='wrk_cls',
        ),
    ]
